### ISSUE TITLE
How to build fast iterators?

### ISSUE THREAD

**Issue by pepijndevos** [JuliaDynamics/ResumableFunctions.jl#67]
Not sure if this is even a bug or how to phrase the question in a useful way...

I'm experimenting with this package and it seems like the struct generated to hold the iterator state has all Any fields.
Is it this package's equivalent of the closure bug?

It seems like your benchmark is getting good performance, are there certain tricks to assure your function produces a fast iterator? Or is it just such a small example that it gets inlined entirely, removing the struct?

I did find that providing very explicit type hints on all variables do propagate to the struct, but wasn't able to figure out how to fix the iterator status and such.

I imagine it's also tricky to specify the element type and length of the resulting iterator, in cases where it is known. Making `collect` switch from the best case typed fixed length collect to the worst case untyped unknown length collect.

For example

```
using ResumableFunctions

bin(s, bins) = Iterators.map(((x, y),) -> (x, searchsortedfirst(bins, y)), s)

@resumable function hysteresis(s)
    bin = -1
    for (x, y) in s
        @yield if iseven(y)
            (x, (bin+1)÷2)
        else
            bin = y
            (x, (y+1)÷2)
        end
    end
end

tolbins(bins, tol=1e-9) = collect(Iterators.flatmap((x -> (x-tol,x+tol)), bins))

hybin(s, bins, tol=1e-9) = bin(s, tolbins(bins, tol)) |> hysteresis
```

Feeding that some iterator like `s = zip(1:1000, rand(1000))`:

```
julia> @time collect(s);
  0.000007 seconds (1 allocation: 15.750 KiB)

julia> @time bin(s, [0.5]) |> collect;
  0.000016 seconds (3 allocations: 15.859 KiB)

julia> @time hybin(s, [0.5]) |> collect;
  0.000391 seconds (8.50 k allocations: 295.484 KiB)

julia> fieldtypes(typeof(hysteresis([])))
(UInt8, Any, Any, Any, Any, Any, Any)
```

In the context of my actual code `s` isn't as simple, and I was seeing 1.5k allocations for collect and 24k allocations for hybin. So even in the case of a more complex iterator the resumable function performs not great.

**Comment by Krastanov** [comment]
It seems that sometime in the last two years there was a significant regression to the benchmarks. What you describe is supposed to be fast (kinda the reason this library was created in the first place), but it was out of maintenance for a few years, so this might be due to a regression in the julia compiler or due to a minor modification in the library that was never tested for performance.

Similar issue is tracked here https://github.com/JuliaDynamics/ResumableFunctions.jl/issues/72

I can not commit to fixing this in the near term, but do not hesitate to ask questions if you decide to give it a try.

**Comment by pepijndevos** [comment]
I'm trying this again on @gerlero's branch, and my conclusion so far seems to be that ResumableFunctions only really work reasonably in concrete typed functions.

Which is kind of a problem if you want to compose functions. You can't really write a function that takes an iterator and produces something with good performance.

```
using ResumableFunctions
using BenchmarkTools

bin(s, bins) = Iterators.map(((x, y),) -> (x, searchsortedfirst(bins, y)), s)

@resumable function any_hysteresis(s)
    bin = -1
    for (x, y) in s
        @yield if iseven(y)
            (x, (bin+1)÷2)
        else
            bin = y
            (x, (y+1)÷2)
        end
    end
end

@resumable function hysteresis(s::Vector{Tuple{Int,Int}})
    bin = -1
    for (x, y) in s
        @yield if iseven(y)
            (x, (bin+1)÷2)
        else
            bin = y
            (x, (y+1)÷2)
        end
    end
end

tolbins(bins, tol=1e-9) = collect(Iterators.flatmap((x -> (x-tol,x+tol)), bins))

hybin(s, bins, tol=1e-9) = bin(s, tolbins(bins, tol)) |> collect

s = collect(zip(1:1000, rand(1000)))

b = hybin(s, [0.5])

println("Any typed")
@btime for _ in any_hysteresis(b) end;
println("Struct types")
println(fieldtypes(typeof(any_hysteresis([(0,0)]))))
println("Vector typed")
@btime for _ in hysteresis(b) end;
println("Struct types")
println(fieldtypes(typeof(hysteresis([(0,0)]))))
```

Result:
```
Any typed
  202.546 μs (11470 allocations: 335.52 KiB)
Struct types
(UInt8, Any, Any, Any, Any, Any, Any)
Vector typed
  2.027 μs (1 allocation: 64 bytes)
Struct types
(UInt8, Int64, Vector{Tuple{Int64, Int64}}, Int64, Int64, Vector{Tuple{Int64, Int64}}, Int64)
```

**Comment by Krastanov** [comment]
I tried to simplify the examples you gave a bit. While not covering everything you mentioned, I think a good first step would be to try to make the following faster:

```
@resumable function one_to_n(n)
    for i in 1:n
        @yield i
    end
end

@resumable function one_to_n_typed(n::Int)
    for i in 1:n
        @yield i
    end
end

function append_one_to_n(n)
    l = typeof(n)[]
    for i in 1:n
        push!(l, i)
    end
    l
end

const n = 100
@btime collect(one_to_n($n)) evals=1;       # 4.258 μs (306 allocations: 11.36 KiB)
@btime collect(one_to_n_typed($n)) evals=1; # 390.000 ns (5 allocations: 1.97 KiB)
@btime append_one_to_n($n);                 # 334.060 ns (4 allocations: 1.92 KiB)
@btime collect(1:$n) evals=1;               # 30.000 ns (1 allocation: 896 bytes)
```

This issue is quite multifaceted. If we start working on it, probably we should split it in smaller pieces along the lines of the topics you have already enumerated (type annotations in the generated structs, the need for function annotation, specialization, reporting length and eltype when possible).

**Comment by pepijndevos** [comment]
There are two avenues I think could be useful.

I found if you do `function foo(x::T) where T` that makes it to the struct,
but not so for any of the locals that depend on T, so indeed one
improvement would be to turn type annotations on locals into struct type
parameters.

How to annotate iterators is still an open problem in this case.

A more radical solution that I've been told is a crime is to defer
code_typed from get_slots to the constructor, a generated function that
uses the argument types as called, rather than as declared to infer struct
types.
