### ISSUE TITLE
tests for downstream breakage 

### ISSUE THREAD

**Issue by Krastanov** [JuliaDynamics/ResumableFunctions.jl#82]
We should probably start running tests against downstream packages given #80 

Here is a typical github action config for downstream tests https://github.com/qojulia/QuantumInterface.jl/blob/main/.github/workflows/breakage.yml

An incomplete list (please edit and add) of packages that can be added

- [ ] ConcurrentSim (the initial reason for the creation of ResumableFunctions)
- [ ] QuantumSavory (the reason I am involved with ResumableFunctions -- a very heavy package though, so having a subset of its tests is something I need to look into)
- [ ] FoldRNA (where issue #80 was detected)
- [ ] Fronts (uses delegation via `@yieldfrom`)

**Comment by gerlero** [comment]
This would be interesting.

Added Fronts to the list of packages that might be tested.
